version: "3.5"
services:
  autoschedule-microservice-client:
    build:
      context: "../"
      dockerfile: "./client/Dockerfile"
    ports:
      - "8091:8091"
    networks:
      - autoschedule-network-proxy-client
    env_file:
      - ../.env
    volumes:
      - ../client:/autoschedule_microservice_client:z
networks:
  autoschedule-network-proxy-client:
    external:
      name: kraken_default
      # use this instead if you still use the old kraken docker-compose
      #name: kraken_default
