version: "3.5"
services:
  autoschedule-microservice:
    build:
      context: "../"
      dockerfile: "./docker/Dockerfile"
    ports:
      - "50051:50051"
    networks:
      - autoschedule-network-proxy
    env_file:
      - ../.env
    volumes:
      - ../app:/autoschedule_microservice:z
networks:
  autoschedule-network-proxy:
    external:
      name: kraken-container-network
      # use this instead if you still use the old kraken docker-compose
      #name: kraken_default
