# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import autoschedule_pb2 as autoschedule__pb2


class AutoScheduleStub(object):
    """The AutoSchedule service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateSchedule = channel.unary_unary(
                '/autoschedule.AutoSchedule/GenerateSchedule',
                request_serializer=autoschedule__pb2.GenerateScheduleInput.SerializeToString,
                response_deserializer=autoschedule__pb2.GenerateScheduleOutput.FromString,
                )


class AutoScheduleServicer(object):
    """The AutoSchedule service definition.
    """

    def GenerateSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AutoScheduleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSchedule,
                    request_deserializer=autoschedule__pb2.GenerateScheduleInput.FromString,
                    response_serializer=autoschedule__pb2.GenerateScheduleOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autoschedule.AutoSchedule', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AutoSchedule(object):
    """The AutoSchedule service definition.
    """

    @staticmethod
    def GenerateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/autoschedule.AutoSchedule/GenerateSchedule',
            autoschedule__pb2.GenerateScheduleInput.SerializeToString,
            autoschedule__pb2.GenerateScheduleOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class HelloWorldStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/autoschedule.HelloWorld/SayHello',
                request_serializer=autoschedule__pb2.Input.SerializeToString,
                response_deserializer=autoschedule__pb2.Input.FromString,
                )


class HelloWorldServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HelloWorldServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=autoschedule__pb2.Input.FromString,
                    response_serializer=autoschedule__pb2.Input.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autoschedule.HelloWorld', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HelloWorld(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/autoschedule.HelloWorld/SayHello',
            autoschedule__pb2.Input.SerializeToString,
            autoschedule__pb2.Input.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
